#ifndef LIBSPROCKETS_GLOBAL_H
#define LIBSPROCKETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBSPROCKETS_LIBRARY)
#  define LIBSPROCKETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBSPROCKETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBSPROCKETS_GLOBAL_H
